// SPDX-License-Identifier: LGPL-2.1-or-later
//
// VPN service layer — wraps libopenlawsvpn FFI in an async Tokio task.
// Communicates with the UI via tokio channels (mpsc commands, broadcast events).

use std::ffi::{CStr, CString};
use std::sync::{Arc, Mutex};

// FFI bindings generated by bindgen in build.rs
#[allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[derive(Debug, Clone)]
pub enum VpnEvent {
    StateChanged(VpnState),
    LogLine(String),
}

#[derive(Debug, Clone, PartialEq)]
pub enum VpnState {
    Idle,
    Connecting,
    WaitingSaml { saml_url: String },
    Connected { server_ip: String, assigned_ip: String },
    Disconnecting,
    NeedReauth,
    Error(String),
}

#[derive(Debug)]
pub enum VpnCommand {
    Connect { profile_id: String, config_path: String },
    SamlTokenReceived { state_id: String, token: String, remote_ip: String },
    Disconnect,
}

pub struct VpnService {
    pub cmd_tx: tokio::sync::mpsc::Sender<VpnCommand>,
    pub event_rx: tokio::sync::broadcast::Receiver<VpnEvent>,
    event_tx: tokio::sync::broadcast::Sender<VpnEvent>,
}

impl VpnService {
    pub fn new() -> Self {
        let (cmd_tx, cmd_rx) = tokio::sync::mpsc::channel::<VpnCommand>(8);
        let (event_tx, event_rx) = tokio::sync::broadcast::channel::<VpnEvent>(64);

        let event_tx_bg = event_tx.clone();
        std::thread::spawn(move || {
            service_thread(cmd_rx, event_tx_bg);
        });

        Self { cmd_tx, event_rx, event_tx }
    }

    pub fn subscribe(&self) -> tokio::sync::broadcast::Receiver<VpnEvent> {
        self.event_tx.subscribe()
    }
}

// Safety wrapper: libopenlawsvpn client pointer is used from a single
// dedicated thread, protected by Mutex. Marking Send is safe here.
struct ClientPtr(*mut std::ffi::c_void);
unsafe impl Send for ClientPtr {}

// Runs on a dedicated OS thread (not async) because libopenlawsvpn blocks.
fn service_thread(
    mut cmd_rx: tokio::sync::mpsc::Receiver<VpnCommand>,
    event_tx: tokio::sync::broadcast::Sender<VpnEvent>,
) {
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("tokio rt");

    rt.block_on(async move {
        let client: Arc<Mutex<Option<ClientPtr>>> = Arc::new(Mutex::new(None));

        while let Some(cmd) = cmd_rx.recv().await {
            match cmd {
                VpnCommand::Connect { config_path, .. } => {
                    let event_tx = event_tx.clone();
                    let client = client.clone();
                    let config_path_clone = config_path.clone();

                    // Phase 1 runs in a blocking thread
                    let handle = tokio::task::spawn_blocking(move || {
                        let c_path = CString::new(config_path_clone).unwrap();
                        let ptr = unsafe { ffi::openvpn_client_new(c_path.as_ptr()) };

                        // Log callback — sends log lines to UI via event channel
                        let tx_log = event_tx.clone();
                        unsafe {
                            ffi::openvpn_client_set_log_callback(
                                ptr,
                                Some(log_callback),
                                Box::into_raw(Box::new(tx_log)) as *mut _,
                            );
                            // D-Bus mode (1 = DBUS)
                            ffi::openvpn_client_set_connect_mode(ptr, 1);
                        }

                        // Store pointer for later use
                        *client.lock().unwrap() = Some(ClientPtr(ptr));

                        emit(&event_tx, VpnEvent::StateChanged(VpnState::Connecting));

                        let result = unsafe { ffi::openvpn_client_connect_phase1(ptr) };

                        // Extract strings before checking — always free to avoid leaks
                        let saml_url = if result.saml_url.is_null() { String::new() } else {
                            unsafe { CStr::from_ptr(result.saml_url).to_string_lossy().into_owned() }
                        };
                        let state_id = if result.state_id.is_null() { String::new() } else {
                            unsafe { CStr::from_ptr(result.state_id).to_string_lossy().into_owned() }
                        };
                        let remote_ip = if result.remote_ip.is_null() { String::new() } else {
                            unsafe { CStr::from_ptr(result.remote_ip).to_string_lossy().into_owned() }
                        };
                        unsafe {
                            if !result.saml_url.is_null() { ffi::openvpn_free_string(result.saml_url); }
                            if !result.state_id.is_null() { ffi::openvpn_free_string(result.state_id); }
                            if !result.remote_ip.is_null() { ffi::openvpn_free_string(result.remote_ip); }
                        }

                        // Validate: a real Phase 1 result has a non-empty SAML URL and state_id
                        if saml_url.is_empty() || state_id.is_empty() {
                            emit(&event_tx, VpnEvent::StateChanged(
                                VpnState::Error("Phase 1 failed — check openvpn3 D-Bus services are running".into()),
                            ));
                            return;
                        }

                        // Open browser and start SAML capture server
                        std::process::Command::new("xdg-open").arg(&saml_url).spawn().ok();

                        emit(&event_tx, VpnEvent::StateChanged(VpnState::WaitingSaml {
                            saml_url: saml_url.clone(),
                        }));

                        // Start SAML capture server — blocks until token received or timeout
                        let token = match crate::saml_server::capture_saml_token(120) {
                            Ok(t) => t,
                            Err(e) => {
                                emit(&event_tx, VpnEvent::StateChanged(
                                    VpnState::Error(format!("SAML login failed: {}", e)),
                                ));
                                return;
                            }
                        };

                        // Phase 2 — send CRV1 token; tunnel comes up asynchronously via D-Bus signals.
                        // We emit Connecting again while waiting; Connected is emitted when
                        // wait_for_disconnect returns (or via D-Bus status, future work).
                        emit(&event_tx, VpnEvent::StateChanged(VpnState::Connecting));

                        let c_state = CString::new(state_id).unwrap();
                        let c_token = CString::new(token).unwrap();
                        let c_remote = CString::new(remote_ip).unwrap();
                        let raw_ptr = client.lock().unwrap().as_ref().map(|p| p.0);
                        if let Some(p) = raw_ptr {
                            unsafe {
                                ffi::openvpn_client_connect_phase2(
                                    p,
                                    c_state.as_ptr(),
                                    c_token.as_ptr(),
                                    c_remote.as_ptr(),
                                );
                            }
                        } else {
                            emit(&event_tx, VpnEvent::StateChanged(
                                VpnState::Error("Client pointer lost before Phase 2".into()),
                            ));
                            return;
                        }

                        // Phase 2 is void — success/failure is determined by the log stream.
                        // The log callback will call emit_state_from_log() on each line,
                        // which transitions to Connected or Error based on the log content.
                        // We do NOT emit Connected here.
                    });

                    let _ = handle.await;
                }

                VpnCommand::Disconnect => {
                    let client = client.clone();
                    let event_tx = event_tx.clone();
                    tokio::task::spawn_blocking(move || {
                        emit(&event_tx, VpnEvent::StateChanged(VpnState::Disconnecting));
                        let mut guard = client.lock().unwrap();
                        if let Some(ClientPtr(ptr)) = guard.take() {
                            unsafe {
                                ffi::openvpn_client_disconnect(ptr);
                                ffi::openvpn_client_free(ptr);
                            }
                        }
                        emit(&event_tx, VpnEvent::StateChanged(VpnState::Idle));
                    })
                    .await
                    .ok();
                }

                VpnCommand::SamlTokenReceived { .. } => {
                    // Handled internally by saml_server; not dispatched externally
                }
            }
        }
    });
}

fn emit(tx: &tokio::sync::broadcast::Sender<VpnEvent>, event: VpnEvent) {
    tx.send(event).ok();
}

// C-callable log callback — forwards lines to the broadcast channel and
// drives state transitions by inspecting the log content.
unsafe extern "C" fn log_callback(message: *const std::ffi::c_char, user_data: *mut std::ffi::c_void) {
    if message.is_null() || user_data.is_null() {
        return;
    }
    let msg = unsafe { CStr::from_ptr(message).to_string_lossy().into_owned() };
    let tx = unsafe {
        &*(user_data as *const tokio::sync::broadcast::Sender<VpnEvent>)
    };

    // Forward raw log line to UI
    tx.send(VpnEvent::LogLine(msg.trim_end().to_string())).ok();

    // Detect tunnel up/down/error from well-known log patterns
    let lower = msg.to_lowercase();
    if lower.contains("connected to") || lower.contains("tunnel is up") {
        tx.send(VpnEvent::StateChanged(VpnState::Connected {
            server_ip: String::new(),
            assigned_ip: String::new(),
        })).ok();
    } else if lower.contains("connectphase2 error") || lower.contains("auth_failed") || lower.contains("authentication failed") {
        // Extract the error message after the "ERROR:" marker
        let detail = msg
            .find("ERROR:")
            .map(|i| msg[i + 6..].trim().to_string())
            .unwrap_or_else(|| msg.trim().to_string());
        tx.send(VpnEvent::StateChanged(VpnState::Error(detail))).ok();
    } else if lower.contains("need_creds") || lower.contains("session expired") {
        tx.send(VpnEvent::StateChanged(VpnState::NeedReauth)).ok();
    } else if lower.contains("disconnected") || lower.contains("tunnel is down") {
        tx.send(VpnEvent::StateChanged(VpnState::Idle)).ok();
    }
}
